% Ação

% Filme 
filme(matrix, acao).
nota(matrix, 8.7).
filme(o_cavaleiro_das_trevas, acao).
nota(o_cavaleiro_das_trevas, 9.0).
filme(gladiador, acao).
nota(gladiador, 8.5).
filme(vingadores, acao).
nota(vingadores, 8.4).
filme(o_protegido, acao).
nota(o_protegido, 7.3).
filme(vingadores_guerra_infinita, acao).
nota(vingadores_guerra_infinita, 8.5).
filme(mission_impossible_fallout, acao).
nota(mission_impossible_fallout, 8.0).
filme(skyfall, acao).
nota(skyfall, 8.0).
filme(john_wick, acao).
nota(john_wick, 7.8).
filme(the_dark_knight_rises, acao).
nota(the_dark_knight_rises, 8.4).

% Série
serie(la_casa_de_papel, acao).
nota(la_casa_de_papel, 8.3).
serie(daredevil, acao).
nota(daredevil, 8.6).
serie(flash, acao).
nota(flash, 7.9).
serie(arrow, acao).
nota(arrow, 7.8).
serie(supergirl, acao).
nota(supergirl, 7.2).

% Anime
anime(naruto, acao).
nota(naruto, 8.5).
anime(one_piece, acao).
nota(one_piece, 8.7).
anime(attacks_on_titan, acao).
nota(attacks_on_titan, 8.9).
anime(bleach, acao).
nota(bleach, 8.3).
anime(boku_no_hero, acao).
nota(boku_no_hero, 8.7).

% Ficção

% Filme
filme(interestelar, ficcao).
nota(interestelar, 8.7).
filme(o_mestre_do_spirit, ficcao).
nota(o_mestre_do_spirit, 8.6).
filme(duna, ficcao).
nota(duna, 8.6).
filme(avatar, ficcao).
nota(avatar, 7.8).
filme(planeta_dos_macacos, ficcao).
nota(planeta_dos_macacos, 8.0).
filme(a_chegada, ficcao).
nota(a_chegada, 7.9).
filme(o_senhor_dos_aneis, ficcao).
nota(o_senhor_dos_aneis, 8.8).
filme(matrix_reloaded, ficcao).
nota(matrix_reloaded, 7.2).
filme(her, ficcao).
nota(her, 8.0).
filme(inception, ficcao).
nota(inception, 8.8).
filme(a_maquina_do_tempo, ficcao).
nota(a_maquina_do_tempo, 7.5).

% Série
serie(stranger_things, ficcao).
nota(stranger_things, 8.8).
serie(black_mirror, ficcao).
nota(black_mirror, 8.7).
serie(westworld, ficcao).
nota(westworld, 8.7).
serie(the_expanse, ficcao).
nota(the_expanse, 8.5).
serie(alienist, ficcao).
nota(alienist, 7.9).

% Anime
anime(steins_gate, ficcao).
nota(steins_gate, 8.8).
anime(psycho_pass, ficcao).
nota(psycho_pass, 8.6).
anime(ghost_in_the_shell, ficcao).
nota(ghost_in_the_shell, 8.3).
anime(cowboy_bebop, ficcao).
nota(cowboy_bebop, 8.7).
anime(ergon, ficcao).
nota(ergon, 8.4).

% Aventura

% Filme
filme(jurassic_park, aventura).
nota(jurassic_park, 8.1).
filme(o_senhor_dos_aneis_o_retorno_do_rei, aventura).
nota(o_senhor_dos_aneis_o_retorno_do_rei, 9.0).
filme(harry_potter_e_a_pedra_filosofal, aventura).
nota(harry_potter_e_a_pedra_filosofal, 8.3).
filme(o_hobbit_uma_viagem_inesperada, aventura).
nota(o_hobbit_uma_viagem_inesperada, 7.8).
filme(piratas_do_caribe, aventura).
nota(piratas_do_caribe, 8.0).
filme(quest_for_fire, aventura).
nota(quest_for_fire, 7.0).
filme(the_lord_of_the_rings_the_two_towers, aventura).
nota(the_lord_of_the_rings_the_two_towers, 8.7).
filme(narnia, aventura).
nota(narnia, 7.5).
filme(guardians_of_the_galaxy, aventura).
nota(guardians_of_the_galaxy, 8.0).
filme(marvels_the_avengers, aventura).
nota(marvels_the_avengers, 8.0).

% Série
serie(game_of_thrones, aventura).
nota(game_of_thrones, 9.3).
serie(friends, aventura).
nota(friends, 8.9).
serie(o_hobbit, aventura).
nota(o_hobbit, 8.1).
serie(stranger_things, aventura).
nota(stranger_things, 8.8).
serie(piratas_do_carambo, aventura).
nota(piratas_do_carambo, 7.6).

% Anime
anime(spirit_digger, aventura).
nota(spirit_digger, 7.8).
anime(attack_on_titan, aventura).
nota(attack_on_titan, 8.9).
anime(one_piece, aventura).
nota(one_piece, 8.7).
anime(demon_slayer, aventura).
nota(demon_slayer, 8.8).
anime(fairy_tail, aventura).
nota(fairy_tail, 8.1).

% Fantasia

% Filme
filme(o_senhor_dos_aneis_a_companhia_do_anel, fantasia).
nota(o_senhor_dos_aneis_a_companhia_do_anel, 8.8).
filme(harry_potter, fantasia).
nota(harry_potter, 8.3).
filme(a_vida_e_bela, fantasia).
nota(a_vida_e_bela, 8.6).
filme(o_senhor_dos_aneis_as_duas_torres, fantasia).
nota(o_senhor_dos_aneis_as_duas_torres, 8.7).
filme(o_senhor_dos_aneis_o_retorno_do_rei, fantasia).
nota(o_senhor_dos_aneis_o_retorno_do_rei, 9.0).

% Série
serie(the_witcher, fantasia).
nota(the_witcher, 8.0).
serie(game_of_thrones, fantasia).
nota(game_of_thrones, 9.3).
serie(stranger_things, fantasia).
nota(stranger_things, 8.8).
serie(the_shannara_chronicles, fantasia).
nota(the_shannara_chronicles, 7.6).
serie(the_mandalorian, fantasia).
nota(the_mandalorian, 8.6).

% Anime
anime(jojos_bizarre_adventure, fantasia).
nota(jojos_bizarre_adventure, 8.6).
anime(demon_slayer, fantasia).
nota(demon_slayer, 8.8).
anime(fairy_tail, fantasia).
nota(fairy_tail, 8.1).
anime(bleach, fantasia).
nota(bleach, 8.3).
anime(fullmetal_alchemist, fantasia).
nota(fullmetal_alchemist, 8.7).

% Drama

% Filme
filme(o_resgate_do_shawshank, drama).
nota(o_resgate_do_shawshank, 9.3).
filme(os_12_homens_decentes, drama).
nota(os_12_homens_decentes, 9.0).
filme(clube_da_luta, drama).
nota(clube_da_luta, 8.8).
filme(forrest_gump, drama).
nota(forrest_gump, 8.8).
filme(a_lista_de_schindler, drama).
nota(a_lista_de_schindler, 9.0).

% Série
serie(breaking_bad, drama).
nota(breaking_bad, 9.5).
serie(the_office, drama).
nota(the_office, 8.8).
serie(friends, drama).
nota(friends, 8.9).
serie(bojack_horseman, drama).
nota(bojack_horseman, 8.4).
serie(the_crown, drama).
nota(the_crown, 8.7).

% Anime
anime(steins_gate, drama).
nota(steins_gate, 8.8).
anime(death_note, drama).
nota(death_note, 9.0).
anime(attack_on_titan, drama).
nota(attack_on_titan, 8.9).
anime(jojos_bizarre_adventure, drama).
nota(jojos_bizarre_adventure, 8.6).
anime(orange, drama).
nota(orange, 8.4).
